### ISSUE TITLE
Sublist3r.py issue 

### ISSUE THREAD

**Issue by maidkhoon** [guelfoweb/knock#113]
Traceback (most recent call last):
File "sublist3r.py", line 21, in
from subbrute import subbrute
File "/home/kali/Downloads/Sublist3r-master/subbrute/subbrute.py", line 18, in
import dns.resolver
ImportError: No module named dns.resolver

**Comment by drego85** [comment]
This is Knock's repository, not Sublist3r!

Go to https://github.com/aboul3la/Sublist3r and open a new issues!
