### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by sajeeshab** [guelfoweb/knock#125]
Traceback (most recent call last):
  File "/home/sajeesh/tools/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
  File "/home/sajeesh/tools/knock/knockpy/knockpy.py", line 12, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/packages/urllib3/response.py", line 9, in <module>
    from ._collections import HTTPHeaderDict
  File "/usr/local/lib/python3.10/dist-packages/requests-2.7.0-py3.10.egg/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by guelfoweb** [comment]
You need python3, pip3, git.
git clone https://github.com/guelfoweb/knock.git
cd knock
pip3 install -r requirements.txt
python3 knockpy.py <DOMAIN>
