### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by Naeem775** [guelfoweb/knock#126]
Hi,
I am trying to run this command from kncok folder
`python3 knockpy.py isecuirty.org`
i have installed all requirements , but i am getting this error 
```
Traceback (most recent call last):
  File "F:\CEH\Work\knock\knockpy.py", line 7, in <module>
    from knockpy import knockpy
  File "F:\CEH\Work\knock\knockpy\knockpy.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by drego85** [comment]
From your terminal install module via:
`pip install requests`
