### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by sqqqs** [guelfoweb/knock#13]
Is it possible to add support Windows? Right now:
Traceback (most recent call last):
  File "C:\knock3\knockpy\knockpy.py", line 19, in <module>
    from modules import core
  File "C:\knock3\knockpy\modules\core.py", line 27, in <module>
    import wordlist
  File "C:\knock3\knockpy\modules\wordlist.py", line 23, in <module>
    from knockpy import get_data
  File "C:\knock3\knockpy\knockpy.py", line 19, in <module>
    from modules import core
ImportError: cannot import name core

**Comment by P3R0** [comment]
Yup,
The Same Issue With Me.
