### ISSUE TITLE
cant load modules ... 

### ISSUE THREAD

**Issue by statix83** [guelfoweb/knock#42]
Traceback (most recent call last):
  File "C:\Python36\Scripts\knock-4.1\knockpy\knockpy.py", line 6, in <module>
    from modules import resolve
  File "C:\Python36\Scripts\knock-4.1\knockpy\modules\resolve.py", line 2, in <module>
    import header
ModuleNotFoundError: No module named 'header'

But there is a header.py in the module folder...

**Comment by wisprp** [comment]
statix83, what shell you are using to run the script?
Check your PATH and PYTHONPATH variables

**Comment by thiru112** [comment]
sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from setuptools import setup
ImportError: No module named setuptools

how to install this its shows error while installing

**Comment by ArminasBek** [comment]
run `sudo apt-get install -y python-setuptools` and then try again

**Comment by slayer321** [comment]
ModuleNotFoundError: No module named 'modules' 

getting this error once  I'm running this command 
knockpy -h

**Comment by jagskap** [comment]
> Traceback (most recent call last):
> File "C:\Python36\Scripts\knock-4.1\knockpy\knockpy.py", line 6, in
> from modules import resolve
> File "C:\Python36\Scripts\knock-4.1\knockpy\modules\resolve.py", line 2, in
> import header
> ModuleNotFoundError: No module named 'header'
> 
> But there is a header.py in the module folder...

Replacing "import header" with "from modules import header" seems to work.

**Comment by Quantum-code72** [comment]
Traceback (most recent call last):
  File "/opt/knock/knockpy/knockpy.py", line 7, in <module>
    from knockpy.lib import output, request, wordlists, report, scan, extraargs, logo
  File "/opt/knock/knockpy/knockpy.py", line 7, in <module>
    from knockpy.lib import output, request, wordlists, report, scan, extraargs, logo
ModuleNotFoundError: No module named 'knockpy.lib'; 'knockpy' is not a package

I'm getting this error

**Comment by itsmetherb** [comment]
File "/home/callmerb/hack/tools/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
ImportError: cannot import name 'knockpy' from partially initialized module 'knockpy' (most likely due to a circular import) (/home/callmerb/hack/tools/knock/knockpy.py)

**Comment by Ravikumararvi** [comment]
> Traceback (most recent call last):
>   File "/opt/knock/knockpy/knockpy.py", line 7, in <module>
>     from knockpy.lib import output, request, wordlists, report, scan, extraargs, logo
>   File "/opt/knock/knockpy/knockpy.py", line 7, in <module>
>     from knockpy.lib import output, request, wordlists, report, scan, extraargs, logo
> ModuleNotFoundError: No module named 'knockpy.lib'; 'knockpy' is not a package
> 
> I'm getting this error
 
Hey
