### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by darkdemon28** [guelfoweb/knock#54]
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
  _  __                 _
 | |/ /                | |   """+__version__+""")?

Getting this error when trying to use the script. Please can we have this issue fixed?

Thanks

**Comment by Sechunt3r** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/knockpy", line 11, in <module>
    load_entry_point('knockpy==4.1.1', 'console_scripts', 'knockpy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/knockpy-4.1.1-py3.6.egg/knockpy/knockpy.py", line 53
    | |/ /                | |   """+__version__+"""            
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
  _  __                 _                
 | |/ /                | |   """+__version__+""")?

**Comment by epi052** [comment]
I'll check it out tonight and submit a PR.

**Comment by epi052** [comment]
follow-up, run it with python2.  the syntax error is when run with python3

**Comment by Rataash99** [comment]
#

> follow-up, run it with python2. the syntax error is when run with python3
----------------------------------------
It's not working with python2 either i've literally tried  everything possible ended up by an unsolved issue 
please, let me know if you find any other fix for this
