### ISSUE TITLE
File "knockpy.py", line 53

### ISSUE THREAD

**Issue by madi10** [guelfoweb/knock#66]
Via Termux (Android)

$ python knockpy.py google.com
  File "knockpy.py", line 53
    | |/ /                | |   """+__version__+"""     
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
  _  __                 _
 | |/ /                | |   """+__version__+""")?

#################
knockpy -h
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/knockpy", line 11, in <module>
    load_entry_point('knockpy==4.1.1', 'console_scripts', 'knockpy')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/knockpy-4.1.1-py3.7.egg/knockpy/knockpy.py", line 53
    | |/ /                | |   """+__version__+"""     
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
  _  __                 _
 | |/ /                | |   """+__version__+""")?

**Comment by mkmozgawa** [comment]
@madi10 This version was written for Python 2, not Python 3. Either run it with Python 2, find a fork that has been rewritten for Python 3, or find another tool for the job. (I'm not the owner / maintainer of this repo, just a friendly person on the Internet.)
