### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by AlphaLabs2302** [guelfoweb/knock#91]
Traceback (most recent call last):
  File "knockpy.py", line 384, in <module>
    main()
  File "knockpy.py", line 326, in main
    print_output(subdomain_resolve)
  File "knockpy.py", line 92, in print_output
    subdomain_csv_list.append(ip_alias+','+str(data['status'])+','+'alias'+','+str(alias)+','+escape_csv(str(server_type)))
  File "knockpy.py", line 75, in escape_csv
    if user_generated_string[0] in ('@','+','-', '='):
IndexError: string index out of range

**Comment by superboy-zjc** [comment]
hi bro, I have the same error as you. Have you found a fix for it?

**Comment by locklocklock** [comment]
same issue！

**Comment by locklocklock** [comment]
> hi bro, I have the same error as you. Have you found a fix for it?

I have tried this method to solve the issue and it works!
1. Go to line 75 of knockpy.py and replace "user_generated_string[0]" to "user_generated_string"
2. Back to "knock" directory and execute "python setup.py install"
3. finished

**Comment by superboy-zjc** [comment]
> > hi bro, I have the same error as you. Have you found a fix for it?
> 
> I have tried this method to solve the issue and it works!
> 
> 1. Go to line 75 of knockpy.py and replace "user_generated_string[0]" to "user_generated_string"
> 2. Back to "knock" directory and execute "python setup.py install"
> 3. finished

谢谢！ :)

**Comment by 5kyw41k3r** [comment]
> > hi bro, I have the same error as you. Have you found a fix for it?
> 
> I have tried this method to solve the issue and it works!
> 
> 1. Go to line 75 of knockpy.py and replace "user_generated_string[0]" to "user_generated_string"
> 2. Back to "knock" directory and execute "python setup.py install"
> 3. finished

Thanks mate
